### ISSUE TITLE
Compile warning when developing in linux kernel with lz4

### ISSUE THREAD

**Issue by lewvan37** [Cyan4973/lz4#139]
Hi:

I got a compile error when I try to develop with lz4 in linux kernel(ver. 3.14):
typedef redefinition with different type: types ('long' vs '__s64' (aka 'long long'))
typedef __INT64_TYPE__ int64_t;
****linux/types.h:312:17 note: previous definition is here
typedef __s64 int64_t;

I think there need another MACRO switch in lz4.c:
#if defined (__STDC_VERSION__) && (__STDC_VERSION__ >=199901L) && (!defined (__KERNEL__))
#include <stdint.h>
#else 
typedef unsigned ...

Waiting for any advice.
Thanks a lot!

**Comment by Cyan4973** [comment]
In which part of `lz4` source does this happen ?

Because within `lz4.c`, there is no int64_t used nor defined.
Closest one is this line
`typedef uint64_t U64;` 
which refers to the _unsigned_ version.

It may seem like a very small different, but within typedef warning, this should be a un-mistakable difference.

**Comment by lewvan37** [comment]
Sorry, I just noticed the header file linux/types.h has been included in lz4.z by myself, in whitch there is  another typedef of int64_t, and it is different with the one in stdint.h.

This issue should be deleted.
