### ISSUE TITLE
Allow writing files without headers (feature request)

### ISSUE THREAD

**Issue by jens-gpio** [Cyan4973/lz4#148]
When including compressed data in code; for instance when writing firmware for microcontrollers, it's a bit tedious to remove the initial (often 11) header bytes.
One really need to write a tool to make sure the correct number of bytes are removed.
Instead I'd like to request a command-line switch on the lz4 utility, which allows to write the raw lz4 data without checksum, starting from the first token.
The reason is that I've just finished writing a decompressor for ARM Cortex-M/Cortex-A (but it can be used by earlier ARM architectures as well) and made it public here for everyone to use:

http://community.arm.com/docs/DOC-10570

-Thus I think there might soon be a lot of people needing only the raw data.

**Comment by Cyan4973** [comment]
Thanks for your excellent Cortex version (I've [linked it](http://cyan4973.github.io/lz4/#other-languages) from lz4 homepage).

Note that the [raw block format](http://cyan4973.github.io/lz4/lz4_Block_format.html) delegates header management to upper layer. Which means, size of compressed data, and size of decompressed data, must be known by other ways (appended in front of compressed data, or implicitly known by the calling program for example).

Could you describe the process you imagine to produce compressed data and then integrate it into flash ?

Regards

**Comment by jens-gpio** [comment]
Thank you for linking to the code. :)
I do not know if it's clearly visible from my code, but currently I detect a 0x0000 offset for determining the end of the compressed data. It might be quicker or better or shorter to compare the source pointer against the end of the source data; I have not agreed with myself on this yet. ;)

I imagine using the following process to generate a compressed file and including it in firmware:
1: Create or modify the uncompressed data (for instance a picture using Photoshop)
2: Use the lz4 command-line tool to compress the data
3: Use a Perl script to cut the compressed data out and write to a binary file (I've done this manually so far)
4: Create a small assembly language file containing a few lines: '.global myPicture; myPicture: .incbin "turtle.rgb"; dcb 0,0'
5: Type make on the command-line; this will build all sources in my src/ directory using gcc/gdc
6: Type make flash on the command-line if the previous make was successful; this will flash the firmware using OpenOCD 0.9.0

When using a Makefile all files ending in .rgb could be automatically compressed using the lz4 utility and an assembly source file could be generated to include the compressed file (using .incbin).
Using .incbin, one can easily place a label before and after the .incbin, then take the difference between those two labels in order to get the length of the data. Alternatively, one can pad 2 zero bytes at the end to produce the terminating match-offset 0x0000.

An alternative, which most users would use, would be to generate a .c file using Perl. This C file would contain an array like this ...

static const uint8_t *gMyPicture[] FLASH = { 0x8f, 0x31, 0x36, 0x61, 0x0a, ..., 0x00, 0x00 };

-The 'FLASH' keyword would place the array in the flash section.
Using C's sizeof, one could find the length of the array, or the decompressor could simply look for the match-offset 0x0000.
So it would probably be useful to be able to output as hexadecimal for embedding into C code.
I know this does not sound very appealing, since we're speaking about compression (using less space), but it would ease the steps for most people (in this case I'm not thinking about myself).

It would be great to be able to output the raw compressed data; the hexadecimal output can in most cases be done by tools like hexdump or a perl script. Of course, as mentioned below, some people do not have the technical knowledge of command-line tools, so they would benefit from a built-in C-file generator.

When not using GCC on the command-line, I believe some people would have to compress the files manually, because developers who work with microcontrollers tend to use IDEs such as KEIL, drag-and-drop features and no scripting. It's probably possible to automate processes in many IDEs, but I have not worked with any Windows based IDEs, so I can't promise anything here. I do not know if the ARM assembler has an INCBIN directive; if it does not, then the best option would probably be to generate a C file.

**Comment by Cyan4973** [comment]
> I do not know if it's clearly visible from my code, but currently I detect a 0x0000 offset for determining the end of the compressed data.

That's pretty interesting, and provides an opportunity for some old genie to get out of the bottle again.
I've been considering using 0x0000 offset for end-of-block-mark for quite some time.

Currently, that's not the case : a 0x0000 offset is simply an invalid offset.
In your case, it nonetheless works because the [frame format](http://cyan4973.github.io/lz4/lz4_Frame_format.html) specifies that a 4-bytes null field ends the frame (followed by an optional checksum). So the compressed block is followed by 4 0x00, 2 of which are misrepresented as the 0x0000 offset. Hence the successfull end detection. But there are still 2 or 6 bytes more in the "compressed" frame produced by `lz4`.

Why hesitating to use 0x0000 offset as an end-of-block mark ?

- It breaks compatibility with existing (deployed) decoders. An encoder using such rule would produce a compressed block incompatible (undecodable) by current crop of decoders.
  + one way to move forward would be to decide that this is a kind of "v2 block format", only decodable by "v2-compatible" decoders. Still, ensuring that the receiving decoder is "v2 compatible", and dealing with special cases ? I smell some future mess ...

- It's incompatible with current API : 
  Current block decoder prototype is : 
  ` int LZ4_decompress_safe (const char* source, char* dest, int compressedSize, int maxDecompressedSize); `
  Its result is the decompressed size. It presumes that the `source` buffer has been entirely consumed. There's no way to tell that it was only "partially" consumed, which makes it impossible for the caller to know that some data from source is still not decoded.

- A "v2-decoder" risk being, by default, incompatible with "v1-produced" compressed blocks
  + since it would never find an 0x0000 offset as end-of-block-mark
  + there is an escape, by introducing some special exception for end-of-block _when_ compressed size is clearly provided (specifically, authorizing to stop at the end of the literal part of the sequence ). But it causes malicious secondary effects in streaming scenarios (see below).

- Relying on it to discover the compressed size makes it impossible to know compressed size beforehand. So it's no longer possible to load exactly a full compressed block for decompression.
  + In fact, the presence of 0x0000 offset only fulfills a role when the caller doesn't know the compressed size of one block. So first there would be a need to find some scenarios in which such condition makes sense (hint : for many scenarios, it doesn't)
  + which means : the caller may load an arbitrary amount of bytes, which could be either too much, or not enough.
    * What to do when the amount of data loaded is not enough to cover a complete block ?
    * Well the expectation would be that the decoder starts nonetheless to decode what's available, and stop when it cannot.

Basically this is the question of _Block-level streaming_ capability. Currently, streaming capability exists at _frame level_, using current blocks as unbreakable entities. Block level streaming open the possibility to work on block pieces, going down to its unitary components, the _sequences_. This used to be impossible, because a literal length can have any size (think about non-compressible data), and must be followed by a match, which could happen any length in the future, potentially well beyond the storage capability of a single buffer. This problem is solved by introducing the 0x0000 offset, which can break an arbitrarily long literal segment into smaller, more manageable, segments.

So these are the end questions : 
- Does _block-level streaming_ make sense, providing some kind of advantage over _frame-level_ streaming ?
- If yes, how to introduce it ___and___ manage compatibility with existing format ?

**Comment by jens-gpio** [comment]
I believe for many reasons you're right; it would be better not to use 0x0000.
What I did was to allocate a buffer and write 0x0000 at compressed[compressedLength] before I started decoding.
-This proves that I already know the length of the compressed data and introduce more possibilities for failures by relying on 0x0000; especially if the compressed data is corrupted by accident (it usually isn't when it resides in Flash memory, as that's read-only).

I believe the best solution for me would be to start by setting up an end-pointer (using register r12), and then compare the source pointer against r12 to see if the end of the compressed data is reached. It would be safer in case some random data occurred in the token, literal length or match offset fields. -decompression of corrupted data would be detected and stopped earlier.
