### ISSUE TITLE
[suggest] building for Android

### ISSUE THREAD

**Issue by joshua5201** [Cyan4973/lz4#153]
I've built lz4 executable for Android with NDK like this according to the [Official Guide](https://developer.android.com/ndk/guides/standalone_toolchain.html) 
```bash
$ /path/to/ndk/build/tools/make-standalone-toolchain.sh \
--arch=arm --platform=android-21 --install-dir=/tmp/my-android-toolchain
$ export PATH=/tmp/my-android-toolchain/bin:$PATH
$ export CC=arm-linux-androideabi-gcc 
$ make
```

Is it proper to add this in Makefile or provide a script about this?

**Comment by Cyan4973** [comment]
Hello @joshua5201 

I believe the point of this documentation is to use the Makefile unmodified,
by just playing with standard environment variables.

It's unclear what could be prepared in advance, since the ndk path seem user-dependent. It would probably require some environment variable to automate something. Or worst case, a scripted probe.
Even the compiler can be different depending on selected target.

If you believe this could nonetheless be scripted for third-party, I guess the `contrib` directory is where this script should be merged (typically `contrib/android`)

**Comment by joshua5201** [comment]
https://android.googlesource.com/platform/external/lz4/+/android-m-preview-2
I found that there is a package in AOSP.

**Comment by Cyan4973** [comment]
good catch !
