### ISSUE TITLE
Size of the Compressed file got increased

### ISSUE THREAD

**Issue by Vishnu-Hacks** [Cyan4973/lz4#191]
I compressed a file with only unique characters to check the performance of the code. It is found that the size of the file got increased by nearly 150%. Which I believe , it happened because of the encoding of the non-matching literals. Please do some changes in the algorithm to encode the literal only if a match has been and found and also only if the encoded literal size is lesser than the uncompressed data.

Thank You!

**Comment by Cyan4973** [comment]
The increased due to encoding is 0.4%.
Everything else is headers.

Considering your result (150%), I suspect the file you compressed was very small.
In which case, the size of headers can be a significant fraction of data to compress (50% in your case).
By default, minimum header size is 4+3+4+4 = 15 bytes.

To compress without header, use `LZ4_compress()` directly at API level.
The command line utility cannot do that, because it must generate a result decodable on many different systems and for different use cases, so it needs the frame headers to ensure decoding success.
