### ISSUE TITLE
size type for input/output value

### ISSUE THREAD

**Issue by foobar** [Cyan4973/lz4#217]
It seems that functions like `LZ4_compress_fast` use int as the size type of input/output buffers, should it be size_t so on 64 bit machine we can process larger data? Or is there any constraint in the algorithm?

**Comment by Cyan4973** [comment]
It's an historical API limitation.

Nowadays, I would use `void*` and `size_t`.
It's more "correct".

But back in these days, I used `char*` and `int` because they felt "natural".
Somehow, I vaguely remember my early days at C programming, it would cost me some time to properly understand and sink in what `void*` and `size_t` mean. They are "strange beast", with weird properties (that only become clear and essential with experience). On the other hand, understanding of `char*` and `int` was immediate. I suspect other junior C programmer would probably feel the same.

Anyway, due to the need for API and ABI stability,
`int` will likely remain there for the foreseeable future.

Newer API use `size_t` instead, for example [lz4frame](https://github.com/Cyan4973/lz4/blob/master/lib/lz4frame.h) .

**Comment by foobar** [comment]
thanks @Cyan4973  
I'm clear now.
