### ISSUE TITLE
Building liblz4 on Windows

### ISSUE THREAD

**Issue by psteinb** [Cyan4973/lz4#51]
Hi to all,

AFAIK the windows installer shipped through
http://fastcompression.blogspot.de/p/lz4.html
but that one only installs the executable binaries. 
Is there any plan (or any way) to build liblz4 (dynamic and/or static) under windows as well?

Best,
Peter

**Comment by t-mat** [comment]
You can build liblz4 with MinGW on Windows :

```
cd /path/to/lz4
make all
```

It will create `lib/liblz4.a` and `lib/libz4.so.1` (DLL).

**Comment by psteinb** [comment]
Thanks that's true. I was looking for a MSVS based solution using the 
command line `cl` compiler. (I am new to Windows ;) ) libtiff did it as 
well. They provide a makefile for Windows.
Best -

**Comment by t-mat** [comment]
I see. If you are using Visual Studio Community 2013, the following command will make static library

```
call "%VS120COMNTOOLS%vsvars32.bat"
cd /d \path\to\lz4
cl -c lib\lz4.c lib\lz4hc.c lib\lz4frame.c lib\xxhash.c
lib lz4.obj lz4hc.obj lz4frame.obj xxhash.obj -OUT:liblz4.lib
```

After that, you can build lz4 command line utility like this :

```
cl programs\lz4cli.c programs\lz4io.c programs\bench.c liblz4.lib /Ilib
.\lz4cli -h
```

But personally, I think directly using `cl` is not good for beginners. Because `cl` has a lot of (over) complicated code generation options and you must choose it carefully.
I think using `msbuild` (`make` for Visual Studio project files) with proper `.vcxproj` (`Makefile` for Visual Studio) is good way for you.

**Comment by Cyan4973** [comment]
Hi Peter

Sorry, there's currently no plan to provide library for Windows as part of the installer.
For now, I can only suggest to follow Takatuki's excellent advises.

Regards

**Comment by psteinb** [comment]
Hi to all -
thanks a lot for the comments. they made me ready to go!
Best -
