### ISSUE TITLE
Can't compile with PIE on 64bit linux

### ISSUE THREAD

**Issue by igoys** [Cyan4973/lz4#53]
Hello I can't compile a program link against lz4 static library on 64bit linux,
command is
g++ -fPIE -pie test.cpp /usr/lib64/liblz4.a -o test

error is
/usr/bin/ld: /usr/lib64/liblz4.a(lz4.o): relocation R_X86_64_PC32 against undefined symbol `memcpy@@GLIBC_2.2.5' can not be used when making a shared object; recompile with -fPIC

I try to recompile lz4 use env CFLAGS="-fPIC" make, but still have that error when I static linking with liblz4.a.

**Comment by igoys** [comment]
Resolved.
I didn't notice "make install" will compile again
Now I can static linking lz4 compile from env CFLAGS="-fPIC" make install

**Comment by Cyan4973** [comment]
Actually, I believe it is a very good point.

It seems to underline that the current Makefile line compiling the static library is not good enough.

The current Makefile is : 

`@echo compiling static library
@$(CC) $(CPPFLAGS) $(CFLAGS) -c $^`

Maybe it needs to be modified to : 
`@echo compiling static library
@$(CC) $(CPPFLAGS) $(CFLAGS) -fPIC -c $^`

Would you mind checking if it works fine for you ?

**Comment by igoys** [comment]
Yes it work.
The previous solution will cut -O3 flag so your's is better, thank you.

**Comment by Cyan4973** [comment]
Ok, I'll modify the Makefile for next release then.

**Comment by Cyan4973** [comment]
Latest version of LZ4 within "dev" branch
https://github.com/Cyan4973/lz4/tree/dev
should correct this issue

**Comment by Cyan4973** [comment]
Well, it appears this change was a bad idea after all.

Not every user needs their static library compiled with -fPIC.
So there is a need to make this setting user controllable, instead of compulsory default, as it is today.
I'll have to revert that change in the version.

Regarding your use case @igoys, it seems it can be properly served by using `CPPFLAGS="-fPIC"`. This was flag would then be added to the list of existing flags, without modifying the initial list.

**Comment by Cyan4973** [comment]
This case underlines a broader issue regarding external management of compilation flags.

As widely accepted, CFLAGS is the environment variable storing C compilation flags.
The problem is that the associated default lz4 Makefile line is pretty long : 

````
CFLAGS ?= -O3
CFLAGS += -std=c99 -Wall -Wextra -Wundef -Wshadow -Wcast-qual -Wcast-align -Wstrict-prototypes -pedantic -DLZ4_VERSION=\"$(RELEASE)\"
````
So you don't want to write this complete list everytime you test a change.

The initial intention was that someone willing to add/modify some flags would simply define them into CFLAGS. It works if you do first :
````
export CFLAGS=-g
make
````
Then the `-O3` will be replaced by `-g`, and all other flags will be present.
Note that you are not limited to a single argument, you can also have a longer line of arguments like this `CFLAGS="-O3 -fPIC"`.

Unfortunately, the above method is considered _bad practice_, because the environment variable stick around after the command. Instead better do something like that : 
````
make CFLAGS=-g
````

This time, CFLAGS will be defined only for current make command.

Unfortunately, the meaning is also slightly different.
This time CFLAGS is firmly defined, and no further modification may happen. It means all other compilation flags are thrown out and won't be used for compilation.

The work around is therefore to add compilations flags to a different line.
Up to now, I've been using CPPFLAGS for this usage. CPPFLAGS doesn't change CFLAGS, and is initially empty, so anything defined into it will be added to the compilation line.

It works, but is a bit hacky, and undocumented. CPPFLAGS is supposed to be used for the Preprocessor, it's not a generic container to add compilation flags on top of CFLAGS, even though it can be used this way.

So what's the better solution ?

One option could be to add a new variable, for example called MOREFLAGS. Anything defined into MOREFLAGS would then be added to CFLAGS without changing it. It's not standard but can be easily documented, and seems easy enough to use. So the only real downside is that someone rushing to modify CFLAGS may not even notice that MOREFLAGS exist.

Another possibility would be to reverse the logic and preserve important compilation into some different variable, for example : 

````
CFLAGS  = -O3 -std=c99 -pedantic
SAFETYFLAGS = --Wall -Wextra -Wundef -Wshadow -Wcast-qual -Wcast-align -Wstrict-prototypes
VERSIONFLAG  = -DLZ4_VERSION=\"$(RELEASE)\"
````
The are then recombined into the final compilation line.

This way, when defining CFLAGS, only the first line is re-defined, all other flags are still preserved. It's slighly more complex to understand what's preserved and what's changed by modifying CFLAGS. But at least now the assumption is that CFLAGS will be played with first, and eventually, the user will take care of more advanced settings by using project specific variables later on.

Well, a little issue, but quite some questions to answer to design a final solution...

**Comment by mwgamera** [comment]
@Cyan4973 If setting an environment variable for a single command without permanently modifying your shell's environment is what you want, then in all shells of Bourne descent you can write:
```
CFLAGS=-g make
```

**Comment by Cyan4973** [comment]
Hi @mwgamera, you are totally right. It is that simple.

**Comment by Cyan4973** [comment]
I've updated the dev branch (c04df7e1b5fb1e4ffa796d2b3d2dea208f7116da) so that it does no longer compile static library with `-fPIC` by default. This flag can still be added on the command line by typing for example `CFLAGS="-O3 -fPIC" make liblz4`, as suggested by @mwgamera.
