### ISSUE TITLE
Introduce '--no-' prefix convention for boolean long commands

### ISSUE THREAD

**Issue by t-mat** [Cyan4973/lz4#62]
Since we recently introduce long commands, I also want to see `--no-` prefix for boolean switches like gcc's [`-Wno-`](https://gcc.gnu.org/onlinedocs/gcc-4.9.2/gcc/Warning-Options.html#Warning-Options) or Ruby OptionPraser's [`--no-`](http://ruby-doc.org/stdlib-2.2.1/libdoc/optparse/rdoc/OptionParser.html) convention.

### What's the point ?

Since command line switches are evaluated left to right order, in some situations boolean switch orverriding is useful.
For example in some `Makefile`

```
# "Default" behaviour
LZ4=lz4 --quiet --force

...
some-target:
    # "Temporary" behaviour
    $(LZ4) --verbose --no-force ...
```

We already have `--quiet` and `--verbose` pair, but currently there is no opposite command for `--force`.

Problem : This may also introduce a lot of boilerplates and redundancy to the command line parser.

**Comment by Cyan4973** [comment]
I fully support the idea of having `--no-` as prefix convention for disabling features.

For example, within latest version, a new long command `--no-frame-crc` has been defined.

That being said, if the point is to say that every command/option should have its inverse `--no-xxxx` available, I'm not sure if it makes sense.

For example, newer long command `--content-size` would then have an inverse `--no-content-size`. But I'm not sure if it makes sense, since `--no-content-size` is the default behavior anyway, so it would equivalent to doing nothing.

**Comment by Cyan4973** [comment]
Since the request is simple enough, I made a new version into the "dev" branch,
with most boolean operators having both their "enabling" and "disabling" variants available.

Doc still only list the "non-default" variants, but their reverse is nonetheless accessible.

There is also an additionnal comment in the "man" page stating that if contrary statements are made on a command line, such as "--X" and "--no-X", only the latest ones is applied.

**Comment by Cyan4973** [comment]
Also, as a minor point : 
note that `--quiet` and `--verbose` are not really boolean opposite.
They influence an output indicator, called `displayLevel`.

`displayLevel` starts at 2, with minimal indications (typically, the result of compression/decompression).
Issuing `--verbose` push it to 4, 
while issuing `--quiet` reduce the level by 1.
As stated into code comments :
`/* 0 : no display ; 1: errors ; 2 : + result + interaction + warnings ; 3 : + progression; 4 : + information */`


Hence `-vq` (displayLevel==3) is not equivalent to `-qv` (displayLevel==4) nor to `-q` (displayLevel==1). 

Little bit tricky, but most users don't need to get into the complexity of combining both options into the same command line...

**Comment by t-mat** [comment]
Thanks for the change and pointing out my misunderstanding !

My main point is "override". Think about gcc's `-Wall -Wextra -Wno-XXX` idiom. If we allow override behaviour, users will be able to write the following command

```
lz4 --content-size --no-content-size ...
```

and vice versa

```
lz4 --no-content-size --content-size ...
```

Obviously this is redundant. But in many cases, lazy users (like me :sunglasses:) tend to set their project's "default" behaviour and sometimes need to override it for compatibility or interoperability. The following is abosolutely artificial example for its usage

```
# Lazy version
# "Default" behaviour
LZ4=lz4 --quiet --force --content-size

...
almost-all-targets:
    $(LZ4) ...

some-target:
    # "Temporary" behaviour
    $(LZ4) --no-content-size ...
```

```
# Strict version
LZ4_BASE=lz4 --quiet --force
LZ4=$(LZ4_BASE) --content-size

...
almost-all-targets:
    $(LZ4) ...

some-target:
    $(LZ4_BASE) --no-content-size ...
```

Also in some extremely strict projects, they like "completely explicit" option settings. In these project, they always tend to avoid utilities default behaviour. I know this manner is quite useful for long-term project.
Because many tools and formats follow the users usage, demands and trends, it will naturally change their default behaviours (eg. compilers). Usually, these changes are good. But in long-term project, these changes increase testing/QA cost. So they like explicit settings.

For help message and document, Ruby and some community use `--[no-]frame-content-size`, `--[no-]frame-crc` style notation for help message.

**Comment by Cyan4973** [comment]
Thanks for references and examples Takayuki.
I believe the need is clear enough.

**Comment by Cyan4973** [comment]
Updated man page, using Ruby convention

**Comment by Cyan4973** [comment]
merged into master
