### ISSUE TITLE
Sign extension issue in LZ4F_readLE64

### ISSUE THREAD

**Issue by eberge** [Cyan4973/lz4#70]
Our static analyzer (Coverity) is complaining about the following line in lz4frame.c:

     value64 += (srcPtr[3]<<24);

saying that the compiler will promote the rhs to a signed 32-bit integer with potential sign extension.  Should probably cast this with something like:

     value64 += ((U64)srcPtr[3]<<24);

**Comment by Cyan4973** [comment]
Thanks for notification

**Comment by Cyan4973** [comment]
Thanks, the reported issue has been fixed in latest version of the "FastMode" branch, alongside an automated test to check its disappearance.

Since coverity was smart enough to discover this problem, I want to their website, and tried to open an account there.

I was hoping for a kind of web/cloud solution, but my understanding is that it's not the right expectation. It seems necessary to download a relatively large software package (~200 MB) to install on local platform.

Is that your experience too ?

**Comment by OrangeTide** [comment]
My experience was the same. I had to unzip about 400MB of java software to run the tool locally to collect results, then upload a .tgz of those results to their cloud "scan" service for it to be analyzed. 
Then I had to wait 1-2 days for someone at Coverity to make sure my open source project meets their guidelines for the free service.
But it does have enough github integration to make it seem fairly painless to use on a day-to-day basis once it is all set up.

**Comment by Cyan4973** [comment]
Is the "local scan software" only used once, 
or is it necessary to run it and upload the result to the cloud each time ?

**Comment by OrangeTide** [comment]
You need to upload a new tarball each time you request a scan. I suspect it's a preprocessor that collects the minimal data needed for it to start analysis. It's a useful tool but a bit of a pain to use it frequently. I've used my calendar to remind myself once a month to do it on my project, which is frequent enough to catch things before a "stable" release but not enough to catch an individual commit that introduced a problem.

You could perhaps try an open source alternative like CLang scan-build and see if it detects this same issue. You can run it locally instead of messing with a cloud service. It's not any less painful to setup initially, but scan-build's command line is way easier to use as part of an automated build/sanity system. (Coverity's commecial tools that runs locally instead of online are also easy to use)

**Comment by t-mat** [comment]
I've never used Coverity, but it has "[Travis CI Integration](https://scan.coverity.com/travis_ci)" section. Also, wifidog-gateway's issue ["Integrate coverity with travis"](https://github.com/wifidog/wifidog-gateway/issues/138) and [their `coverity_scan` branch](https://github.com/wifidog/wifidog-gateway/commits/coverity_scan) seems helpful for us.

**Comment by Cyan4973** [comment]
Thanks, clear enough.

scan build is already part of current lz4's CI. See for example : 
https://travis-ci.org/Cyan4973/lz4/jobs/56936461

and it's good. But since coverity caught one thing that evaded scan-build, I was curious to see how hard/easy it would be to integrate.

Thanks for the links Takayuki !

**Comment by eberge** [comment]
Yes, I've only used it as a downloaded package.  If they have other
options, I simply was unaware of them.

And getting access to it might be a bit pricey, but I'm not sure whether
there are smaller sizes packages that might be more economical (for our org
it's complicated enough that that we have someone else who's maintaining
the relationship with Coverity and we have to go through them to get
licenses...).

Thanks for the quick response on this!

Eric

**Comment by Cyan4973** [comment]
There's a new "coverity_scan" branch, at https://github.com/Cyan4973/lz4/tree/coverity_scan.
It automates the process of sending new sources to coverity for static analysis.
I believe it covers all the points opened in this issue.
