### ISSUE TITLE
[fastMode] No LZ4_compress_fast_limitedOutput

### ISSUE THREAD

**Issue by nemequ** [Cyan4973/lz4#78]
I was just looking at the fastMode branch, and I noticed that LZ4_compress_fast takes a maxOutputSize parameter, unlike compress and compressHC, and that there is no LZ4_compress_fast_limitedOutput.

I don't really mind there being no unsafe version, but you might want to consider renaming compress_fast to compress_fast_limitedOutput for two reasons: (1) consistency with existing APIs, and (2) gives you room to add an unsafe compress_fast in the future without weird naming (although LZ4_compress_faster would be funny…)

**Comment by Cyan4973** [comment]
The argument regarding naming consistency is good.

I'm at odd with the better solution to move forward.

The initial API of LZ4, from which `LZ4_compress()` originates, was designed years ago, at a time when I had much less experience and feedback on how the API is actually used. Back then, the simpler `LZ4_compress()` served 2 purposes :

1. simple to read and use
2. speed optimization

While point 1 proved successful, point 2 was later superseded.

The main idea was that if there is no "end of output buffer" to pay attention to, that's one less test to worry about, speeding up the process. And it works. But now, there is an "implicit" responsibility on the caller, which must ensures that the output buffer is large enough (using `LZ4_compressBound()`). Even documented, that's still a liability.

I now prefer to make this guarantee explicit : the output buffer size must be provided into the argument list, it is checked against `LZ4_compressBound()`. If it's large enough, it triggers the "fast path". If not, the function either refuses to proceed, or implements additional checks to ensure it does not bleed beyond buffer limits. It properly and safely solves point 2.

Retrospectively, the simpler API was a mistake. But it took time to learn it, and now, `LZ4_compress()` is part and centerpiece of LZ4 API, so it can't be removed.

It's fair to say that Point 1, regarding readability and simplicity of API, is not helped by this new methodology. Adding just another argument looks like very little added complexity, and indeed, it is small, but every little complexity acts as a deterrent for future users.

So, could it be removed ? Unfortunately, I'm now convinced that C is far too fragile, and gives way too much power and responsibility into the hands of developers. It is not a good language for everyday programming. By everyday programming, I mean some quite normal expectations from junior, casual and even relaxed programmers, as we would all like to be. We don't want to pay attention to 32-bits overflow when our values are going to stand roughly between 0 and 10. We don't want to pay attention to buffer overflow for every read, to memory leaks for every little object, and so on. Not just damned rookies, look for example at `memcpy()`, at `strcpy()`, ultra-standard grand-daddy C library functions. They don't provide any buffer overflow check. They don't care, and don't even invite the programmer to care, just silently transferring responsibility into his hands. Because in fact, no one wants to care about such mechanical issues, we wish they should be *automatically* detected and taken care of by the compilers.

But they are not. Not in C. Which means that, no, unfortunately, I don't think it's a good idea to remove that check. And therefore, I don't plan to implement any future API without an explicit mention of every buffer size.

**Comment by nemequ** [comment]
I have no problem with the decision to not have an unsafe version (*especially* as the default—LZ4_compress and LZ4_compress_unsafe would be much better).  IMHO the unsafe versions are just asking for trouble, and the performance difference.

I take a similar approach in Squash regarding the fast path—users have to provide the buffer size, but plugins can provide unsafe versions which will be called if size >= compressBound.  If a plugin *only* provides an unsafe version and size < compressBound I'll actually allocate a temporary buffer and compress to that, then memcpy the result back into the original buffer (or return an error if there isn't enough room).

This is getting a bit off-topic, but for C in general one thing that would really help here is using [conformant array parameters](https://www.securecoding.cert.org/confluence/display/c/API05-C.+Use+conformant+array+parameters) to tell the compiler (and static analyzers) how big the buffers are.  Unfortunately it's C99 only, and IIRC last time I checked MSVC doesn't support it.  Still, it's the one API change for Squash I'm really considering, especially since you can now use clang with VS…  I'm sick of catering to MSVC—I can understand not yet supporting C11, but the lack of full C99 support is absurd.  MSVC is the new IE.

Maybe you could just add a note to the documentation of compress_fast… something like "Note that there is no LZ4_compress_fast_limitedOutput, and there never will be."  If people see that at least they will know that the situation is intentional.

Another thing that could help would be formally deprecating LZ4_compress in favor of LZ4_compress_limitedOutput (as well as other similar functions).  For GCC/clang/ICC you could even do __attribute__((__deprecated__("use LZ4_compress_limitedOutput instead")))

**Comment by Cyan4973** [comment]
Yeah, if I could I would make `LZ4_compress_limitedOutput()` the new `LZ4_compress()`.
But this would be a breaking change, with difficult to evaluate consequences on the user side.

So I'm stuck, and need to continue supporting `LZ4_compress()` as it is.

Now that we are talking about it, what I could do, nonetheless,
is to make `LZ4_compress_limitedOutput()` the new "default",
by putting it prominently at the top of the list within `lz4.h`.

At the same time, I could continue to support LZ4_compress(), but declare it "obsolete",
in order to discourage its usage.

**Comment by Cyan4973** [comment]
Well, while at it, I could even rename it `LZ4_compress_safe()`, for more coherent naming convention,
since the 2nd advertised function is `LZ4_decompress_safe()`.

The older name would still be supported, of course, but within the "obsolete" section.

**Comment by nemequ** [comment]
If you do I hope you'll also mark it as deprecated with a function attribute.  Old code will still build without issue, it will just trigger a warning.

**Comment by t-mat** [comment]
:+1: for

 - More coherent naming
 - Deprecating, slowly.

But

 - Provide some flags to disable deprecation to support "Zero warning" policy. e.g. [`_CRT_SECURE_NO_WARNINGS`](https://msdn.microsoft.com/en-us/library/8ef0s5kh.aspx))
 - All obsolete/deprecated functions need document and migration guide.

Offtopic : If we will keep compatibility with C++98..14, we should avoid array constraints in the prototype. Even `extern "C"` is indicated, C++ compiler could not accept it.

```
// https://ideone.com/mCUZA6
extern "C" int f(unsigned n, int a[n]);
int main() {}

Error (g++4.9.2, -std=c++14)
prog.cpp:1:37: error: use of parameter outside function body before ']' token
 extern "C" int f(unsigned n, int a[n]);
                                     ^
```

**Comment by nemequ** [comment]
> Provide some flags to disable deprecation to support "Zero warning" policy. e.g. _CRT_SECURE_NO_WARNINGS)

[-Wno-deprecated-declarations](https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html)?  Or, if you prefer to do it in code, you could use [diagnostic pragmas](https://gcc.gnu.org/onlinedocs/gcc/Diagnostic-Pragmas.html).

> Offtopic : If we will keep compatibility with C++98..14, we should avoid array constraints in the prototype. Even extern "C" is indicated, C++ compiler could not accept it.

Interesting.  I guess the only way to do this safely would be to define a macro, something like (untested):

```C
#if defined(__STDC_VERSION__) && __STDC_VERSION__ >= 199901L
#define ARRAY_LENGTH(n) n
#else
#define ARRAY_LENGTH(n)
#endif
```

Anyways, it will not work for LZ4 because the length parameter has to precede the buffer, so it would require an API/ABI break.

**Comment by t-mat** [comment]
>> Provide some flags to disable deprecation to support "Zero warning" policy. e.g. _CRT_SECURE_NO_WARNINGS)

> -Wno-deprecated-declarations? Or, if you prefer to do it in code, you could use diagnostic pragmas.

Since LZ4 supports quite old compilers and always prefer to take standard/portable way, I suppose it may be implemented as some conditional macro like [this answer at Stackoverflow](http://stackoverflow.com/a/295229/2132223).

```
#if !defined(LZ4_DISABLE_DEPRECATED_ATTRIBUTE) && !defined(LZ4_DEPRECATED)
#  if defined(__GNUC__)
#    define LZ4_DEPRECATED(func) func __attribute__ ((deprecated))
#  elif defined(_MSC_VER) && (_MSC_VER >= 1310) // since MSVC 2003
#    define LZ4_DEPRECATED(func) __declspec(deprecated) func
#  endif
#endif
#if !defined(LZ4_DEPRECATED)
#  define LZ4_DEPRECATED(func) func
#endif

LZ4_DEPRECATED(void* LZ4_create (const char* inputBuffer));
```

**Comment by nemequ** [comment]
That's pretty ugly.  IDK when GCC started supporting attributes before the functions, but I'm pretty sure `#if defined(__GNUC__) && (__GNUC__ >= 4)` would be safe.  If someone is using GCC 3.x they are probably pretty comfortable with deprecated code—I think making it more readable for everyone else is more important than triggering a warning for people running GCC < 4.

**Comment by t-mat** [comment]
Yeah, it's ugly :weary:  I hope Yann will handle this well.

According to glib, `__deprecated__` attribute is implemented since gcc 3.1

 - https://git.gnome.org/browse/glib/tree/glib/gmacros.h?id=3fa0a051a47ca9e7ddcaf56cf842dc133fceede9#n105

```
#if    __GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 1)
#define G_GNUC_DEPRECATED __attribute__((__deprecated__))
#else
#define G_GNUC_DEPRECATED
#endif /* __GNUC__ */
```

**Comment by Cyan4973** [comment]
There's a new API proposition within "dev" branch :  2f8a4c32f998e6440a0b580996ecf8f101df2c74

As suggested, it drops previous compression functions in favor of `LZ4_compress_safe()`.

Older functions are still supported, they are listed in the "obsolete" section.

Regarding the process of phasing out older code,
this is a fairly long process, due to the very large user base.

I intend to have several phases : 

1. New function introduced, older ones supported in "obsolete" section
2. Add warnings on older "obsolete" prototypes
3. Comment out prototype into *.h. Keep the code into *.c
4. Comment out the code into *.c
5. Remove dead code

Each stage should expect to last a few months, at least. They are not equivalent of course. Reaching stage 5 is faster than reaching stage 3 typically.

Anyway, regarding the latest changes, they are still at phase 1, which means no warnings. It's too soon. I may learn or discover something and change my mind. It already happened in the past, on a few limited occasions. So it's not the right time push the entire ecosystem towards the new API.

That being said, I already have a few functions within "obsolete" section waiting to reach stage 3, and they are prime candidate to be elected at stage 2, with an associated waiting. So, expect an update on this, taking into consideration your propositions.

**Comment by t-mat** [comment]
I'm quite comfortable with these lines :tropical_drink::sunglasses:

```
int LZ4_compress_safe (...);
int LZ4_decompress_safe (...);
```

Anyway, I would like to add 2 phases

 - 2.1 : Announcement of removal schedule
 - 3.1 (or 4.1) : Major version update

I think even deprecated, same API/ABI should be provided in same major version.

**Comment by Cyan4973** [comment]
These are all good points @t-mat 

Only issues I can think of : 
 - 2.1 : I typically have no idea about when the obsolete function is going to be completely removed. It always tends to be longer than expected.
 - 4.1 : Major version update. 
There is this implicit rule that any breaking change should increase the major version number.
In usual circumstances, it's a no brainer. But for this case, I wonder.

Let's suppose the plan worked as planned, and after almost 2 years in "obsolete" mode, some obsolete  functions are getting finally retired (i.e. commented out , since this is stage 4).
OK, at this point in time, the prototype has been issuing a "warning" for a long time already, and there was even a period of "prototype removed (commented) from .h". So anyone still using it had a change to notice the miss and complain about it.

Which means, at this moment, the expectation is that no more user is left. Or at least, no more user with some code which can still evolve.

Moving up the major version number in such circumstance begs for questions. LZ4 has quite a long list of deprecated functions already. If the major number has to be increased each time one of the deprecate function is removed, it will quickly reach v10 and beyond.

Is that acceptable ?

For example, I don't see other libs moving their major number that fast.
I also see that the major version number is tied to the library name.
So I'm not sure if it is really without "problem" for the vast majority of "normal" users. For example, maybe the naming change will break something in some administrator script.

So my feeling is that it is trading a risk for another risk.
But one looks small, and the other is unknown.

I guess the issue is that everyone will have a different appreciation of the size of each of those risks.

**Comment by nemequ** [comment]
For steps 3 and 4, instead of commenting them out, maybe hide them behind an ifdef (LZ4_ENABLE_DEPRECATED or something)?

With a major version bump it would be quite reasonable to change the API a bit more drastically (and suddenly).  For example, move compress/decompress_safe to compress/decompress.  You don't want to do this very often, but maybe it wouldn't be a bad idea to do it at some point in the relatively near future.  IMHO if you do bump the major version you should take the opportunity to remove all deprecated code, and clean up the API where it makes sense.  If nothing else that means you don't have to do it nearly as often, and its very common for distros to ship multiple major versions side-by-side until there are no more users of the old version, so you get out of having to deal with most of the steps you mentioned above.

Personally, I would do steps 1 and 2 at the same time, then wait for a while.  Once you're satisfied with the new APIs bump the major version, drop all the deprecated code, rename anything you want to rename (e.g., move LZ4_compress/decompress_safe to LZ4_compress/decompress).  People who want to keep using the old APIs can use the old library.  The only real difficulty is if a project wants to use the new API but links to a library which uses the old API…  TBH I doubt that will be much of an issue for LZ4 (it was a big problem for GTK+ 3), but if you wanted you could solve it by changing the symbol prefix (e.g., lz4_* instead of LZ4_*).

**Comment by t-mat** [comment]
I suppose "Announcement" and "Major version bump" as some kind of barrier.  As before, we will iterate phase 1 and 2 until new major version plan will be completed, so we will not reach "v10" soon.

```
                                                (Backport: critical bug fix)

                                        ------------------[v1.z.1]
                                       /                     /
                                      /                     /
[v1.0]--[v1.1]--...--[v1.z (final)]--+---------+--[v2.0]--[v2.1]-- ...
                 ^                    \       /     ^
                 |                     \     /      |
                 |                  [dev/pre-v2]    |
                 |                                  |
           "Announcement"                  "Next major version"
```

I also suppose these "Major" changes will advance quite slowly or never happen.  Because currently there is no big problem which need to change API/ABI/Format completely.

So I :+1: to stick with "v1" and keep consistency for now.

**Comment by Cyan4973** [comment]
OK, thanks, sounds like good advises :+1:

**Comment by Cyan4973** [comment]
lz4 and lz4hc have been updated to use the new naming convention `LZ4_compress_safe()`.
It's still necessary to these new names into user programs, but for the time being, nothing breaks, since all current names are just redirected towards the newer ones.

In addition, warning messages are now implemented. They check all the functions that were declared "obsolete" for some time now. It should prove useful in pushing user programs to update towards the maintained versions.

Both modifications can be accessed at "dev" branch : https://github.com/Cyan4973/lz4/tree/dev

I guess it covers the points opened within this issue.

**Comment by Cyan4973** [comment]
I just noticed that
`LZ4_compress_fast()` is a super-set of `LZ4_compress_safe()` : 
when `acceleration == 1`, `LZ4_compress_fast()` is equivalent to `LZ4_compress_safe()`.

I wonder if this could be used to reduce API complexity (i.e. reduce the number of functions displayed within `lz4.h`).

I also worry a bit that the naming `LZ4_compress_safe()` implicitly imply that other versions are _unsafe_, which is not true. The only reason `LZ4_compress_safe()` got his name is that a name different than `LZ4_compress()` was required, and this one looked more logical when being displayed just in front of `LZ4_decompress_safe()`

Well, there are just opened questions, while currently wondering about "cleanness" and user perception of LZ4 API, in anticipation for an r129 release.

**Comment by nemequ** [comment]
I think it would be very nice to combine compress_fast, compress_safe, and compress_HC into a single API.  What I'm planning for Squash is:

* 1 -> fast(32)
* 2 -> fast(24)
* 3 -> fast(17)
* 4 -> fast(8)
* 5 -> fast(4)
* 6 -> fast(2)
* 7 -> safe
* 8 -> hc(2)
* 9 -> hc(4)
* 10 -> hc(6)
* 11 -> hc(9)
* 12 -> hc(12)
* 13 -> hc(14)
* 14 -> hc(16)

If you want to make a clean break from the old API, how about either LZ4_encode/decode or lz4_compress/decompress?  If you want to go that route, a few things which would be nice (IMHO) for a new API:

* As discussed, safe (at least for the defaults—I don't really care if there are unsafe alternatives or not).
* Also as discussed, [conformant array paramenters](https://www.securecoding.cert.org/confluence/display/c/API05-C.+Use+conformant+array+parameters) for >= C99.  Just to help compilers and static analyzers.
* Use an unsigned type, something larger than int, for lengths.  INT_MAX is only guaranteed to be 2^15-1, though in practice it's probably safe to assume 2^31-1.  Still, that's not exactly a huge piece of data.  I don't think the C standard actually makes any guarantees about SIZE_MAX, but I think it should be pretty safe to assume >= 2^32 (AFAIK size_t is usually the word size, so for 64 bit systems it should be 2^64).  intmax_t is probably overkill, but uintptr_t or uint64_t would probably be okay.  You may think this is overkill because nobody wants to load that much data into RAM, but keep in mind that this can be used with memory mapped files.

So something like

```C
size_t
lz4_compress (size_t compressed_length,
              uint8_t[LZ4_LENGTH_PARAM(compressed_length)] compressed,
              size_t uncompressed_length,
              uint8_t[LZ4_LENGTH_PARAM(uncompressed_length)] uncompressed,
              int level);
```

If you want to be a bit more expressive in the return value (beyond just 0 == failure), you could do what Squash does:

```C
LZ4_statusCode
lz4_compress (size_t* compressed_length,
              uint8_t[LZ4_LENGTH_PARAM(*compressed_length)] compressed,
              size_t uncompressed_length,
              uint8_t[LZ4_LENGTH_PARAM(uncompressed_length)] uncompressed,
              int level);
```

I'm actually not sure how conformant array parameters work here, but that's not the point—return a status code, and compressed_length becomes an in/out parameter.

**Comment by Cyan4973** [comment]
Actually @nemequ , the lz4frame API is planning to be the one you describe.
It's already fairly close.

**Comment by nemequ** [comment]
Yes, the lz4frame API is (IMHO) much nicer.  Obviously the preferences part is more complicated than the lz4 API needs to be, but the only thing I really dislike about it is that LZ4F_compression/decompressionContext_t are typedefs to void* (which has some unfortunate implications for type safety).  Moving the lz4 API, at least the public parts, seems like a good idea.

**Comment by Cyan4973** [comment]
Indeed,
I'm keeping the "major version number" for such "big bang" API update.
And yes, the ideal "prototype" would be fairly close to what lz4frame is today.

I agree lz4frame has a lot more options to select from, which can be confusing.
It also has a lot more responsibilities.
So they are effectively at different layers.

The only minor point where I do not necessarily agree is about the use of `void*` pointers.
This is a common way to say "I'm not making any assumption about what's being provided".
Internally, it is converted into a table of bytes, which is probably the lowest possible assumption, as there is no alignment required.

I also like the way you use array parameters to embed object size, which is great.
It's just that I don't feel like abandoning non-C99 compilers yet. It's too soon. I still receive a lot of reports from people using non-C99 compilers. Maybe in the future this situation will change.


The "big bang" API update is not planned for now.
This is something for much later, like 2016 or so.


Regards

**Comment by Cyan4973** [comment]
> I'm considering changing this typedef to `size_t*`, which would at least embed some alignment requirement.

Humm, `size_t*` is not enough. I forgot I have some `U64` members too. On 64-bits systems, it's not a problem since `size_t` is also 8 bytes. But on some 32-bits systems, it is. ARM cross-compilation test fails on this.

Strangely, clang doesn't complain when compiling for 32-bits x86. But maybe `U64` may be stored with only 32-bits alignment on such system.

**Comment by nemequ** [comment]
Why would you need to worry about the alignment of a pointer?  It's the alignment of the object it points to that matters, the pointer only needs to be aligned to whatever `_Alignof(void*)` is (which is the same as `_Alignof(size_t*)`, or any other pointer).

If I were you I would just make them typedefs to incomplete types—that's how people usually deal with private data in C.  Something like:

```C
typedef struct LZ4F_compressionContext_s* LZ4F_compressionContext_t;
```

Then, in `lz4frame.c` you can declare the struct.  C is fine with you passing around **pointers** to an incomplete type.

> I also like the way you use array parameters to embed object size, which is great.
> It's just that I don't feel like abandoning non-C99 compilers yet. It's too soon. I still receive a lot of reports from people using non-C99 compilers. Maybe in the future this situation will change.

That's the point of the `LZ4_LENGTH_PARAM` macro—see [my earlier comment](https://github.com/Cyan4973/lz4/issues/78#issuecomment-91092151).  For C++ or C < C99, the preprocessor will convert it to nothing, it would only actually be the length for C >= C99.

Also, two more things I just remembered: the input data should be const, and both the input and output should probably be restricted (with a macro like the one described above, since restrict is C99).

**Comment by Cyan4973** [comment]
> Why would you need to worry about the alignment of a pointer? It's the alignment of the object it points to that matters

Yes, that's what I meant.
As per #79, this is what achieves the new typedef.

> If I were you I would just make them typedefs to incomplete types

I wasn't aware of this technique.
I'll look a bit more into it.

> see my earlier comment. For C++ or C < C99, the preprocessor will convert it to nothing, it would only actually be the length for C >= C99.

OK. Sorry, it totally evaded my attention.
I'll also take a look at it.
It could be that this specific proposition might not be possible while preserving current API for non C99 compilers, since it seems to impose an order within parameters (length before tables).
But that's nonetheless a could idea to look at, if only for future proptotypes.

Regards

**Comment by nemequ** [comment]
> It could be that this specific proposition might not be possible while preserving current API for non C99 compilers, since it seems to impose an order within parameters (length before tables).
> But that's nonetheless a good idea to look at, if only for future proptotypes.

Yes, it does require the length argument to precede the buffer, so it could only be used for new functions :(

You also wouldn't be able to use void*, so there could be some casting required if people want to pass a char[] (or whatever) and the API used uint8_t[].  IMHO it is well worth it to be able to provide the extra info for compilers and static analyzers… switching void* to uint8_t[] could also be considered an API break for this reason, so again, not really possible for the old APIs.

**Comment by Cyan4973** [comment]
Coming back to earlier https://github.com/Cyan4973/lz4/issues/78#issuecomment-95488068 : 

LZ4 currently proposes prominently these 2 compression functions : 
 - `LZ4_compress_safe(...)` : the usual compression function, fast version
 - `LZ4_compress_fast(..., acceleration)` : the new version which can be even faster (and compress less) depending on acceleration parameter.

Let's remind, by the way, that non-C99 compilers do not allow overloaded function names, nor default parameter values. Otherwise, it would be simple to fuse the above 2 functions into a single one.

I feel that it's still a good idea to have a "primary" function with as few parameters as possible, to ease learning curve. Hence without "acceleration" parameter, which can be confusing. 

One remaining point is if the selected names are good enough.

A few alternatives I have in mind : 
 - `LZ4_compress_fast(...)`
 - `LZ4_compress_faster(..., acceleration)`

or
 - `LZ4_compress_default(...)`
 - `LZ4_compress_fast(..., acceleration)`

or
 - `LZ4_compress_simple(...)`
 - `LZ4_compress_fast(..., acceleration)`

Not a big change. The only objective it achieves is to remove `LZ4_compress_safe()` name, which could imply that other alternatives are unsafe (since it's the case for `LZ4_decompress_*()`).

A looming question behind is that,
sure it's good to have a "prominent" function which is as simple as possible.

But for "advanced" ones, which are targeting advanced users anyway, it looks less clever.

Therefore, rather than having 2 close alternative functions, such as : 
 - `LZ4_compress_safe_continue(...)`
 - `LZ4_compress_fast_continue(..., acceleration)`

It could be more appropriate to have a single one : 
 - `LZ4_compress_fast_continue(..., acceleration)`

One could argue that it is in fact less confusing to have less (overlapping) choices.

**Comment by Cyan4973** [comment]
I've been reading a bit on incomplete types in C lately.

One of the clearest sources I could find is referenced here : http://docs.oracle.com/cd/E19205-01/819-5265/bjals/index.html. Good mention also for this entry : http://www.embedded.com/electronics-blogs/programming-pointers/4024893/Incomplete-types-as-abstractions

So these reads make it clear that incomplete types are a good way to encapsulate private members.

My only minor complaint is that, compared to a pointer to `long long` (for example), pointer to incomplete type lose the alignment requirement, making them effectively less strict (in this aspect).

I haven't yet tested it, but I also wonder if incomplete types allow stricter compilation checks than `void*`. I hope so, otherwise they would only be slightly more convenient, which does not look great enough. Well, let's make some tests to see that...

**Comment by Cyan4973** [comment]
I played with "pointer to incomplete types : compilation checks", as suggested within last post.

The compiler would successfully detect a wrong swap of incomplete types (such as using `decompressionContext*` instead of `compressionContext*`).

On the other hand, it would happily accept a `void*` pointer, instead of the right pointer to incomplete type, without triggering any warning.

It seems compiler can make some sorts of type checks with incomplete types, but not all.

**Comment by nemequ** [comment]
Regarding the functions; I think one function would be fine.  Especially if there is documentation, and a suggestion for a default value for people who would have been happy with the shorter function.  A define for something like LZ4F_ACCELERATION_DEFAULT could also help make the API a bit more self-documenting… using an enumeration instead of an int would help even more, but I don't think that's feasible here since there are too many potential values.

One thing that is a bit confusing is that a higher value means faster but worse compression.  I think everyone is used to a higher value correspond to slower, but better compression.  LZ4HC is the obvious example, but also think about zlib/gzip, bzip2, lzma/xz.  In *every* compression API I can think of (other than this one), higher numbers = slower or more memory, better ratio.

As for the alignment issue, a *pointer* to long long has the same alignment requirement as a *pointer* to any other type, including an incomplete type.  The caller has no way of knowing the size of an incomplete type, so it can't allocate one, so it has no need to know the alignment.

Most compilers will emit a warning (depending on the flags, of course) about trying to pass a pointer to a type other than the expected one.  For example, if I do

```C
LZ4F_compressionContext_t ctx;
LZ4F_createCompressionContext (&ctx, LZ4F_VERSION);
LZ4F_compressBegin (&ctx, …);
```

Currently the C compiler will accept it without complaint.  If the context were a typedef to a pointer to an incomplete type instead of void*, there would be a warning.

This is actually something I've done with the existing API.  It's a pretty common pattern for when the type you're working on is intended to be placed on the stack, so it's one of those mistakes that can actually be easier to make for people with more experience in C.  It's especially confusing because you typedef away the indirection operator, so it really feels like one of those stack-based APIs at first.  Unfortunately I think you're stuck with typdefing away the indirection operator since fixing that would require an API break.

**Comment by nemequ** [comment]
> On the other hand, it would happily accept a void* pointer, instead of the right pointer to incomplete type, without triggering any warning.

void pointers in C are interchangeable with any other pointers.  That's why `Foo* bar = malloc(sizeof (Foo))` is perfectly acceptable (and even encouraged) in C, but not C++.  When you use void* you're basically opting out of type checking.

**Comment by nemequ** [comment]
> As for the alignment issue, a pointer to long long has the same alignment requirement as a pointer to any other type, including an incomplete type.

So it turns out this isn't quite true.  Per the [C11 specification](http://www.open-std.org/jtc1/sc22/wg14/www/docs/n1570.pdf) (§ 6.2.5, paragraph 28):

> A pointer to void shall have the same representation and alignment requirements as a pointer to a character type. 48) Similarly, pointers to qualified or unqualified versions of compatible types shall have the same representation and alignment requirements.   All pointers to structure types shall have the same representation and alignment requirements as each other.   All pointers to union types shall have the same representation and alignment requirements as each other.   Pointers to other types need not have the same representation or alignment requirements.

So technically if you used a pointer to `long long`, then cast that to a struct for internal usage in LZ4, the result is undefined.  I doubt there has ever been a system built where the alignment of a pointer to `long long` is different from the alignment of a pointer to a struct, but it is technically possible…

**Comment by Cyan4973** [comment]
> The caller has no way of knowing the size of an incomplete type, so it can't allocate one, so it has no need to know the alignment.

Very good point.

> For example, if I do
> `LZ4F_compressionContext_t ctx;`
> `LZ4F_createCompressionContext (&ctx, LZ4F_VERSION);`
> `LZ4F_compressBegin (&ctx, …);`
> Currently the C compiler will accept it without complaint. If the context were a typedef to a pointer to an incomplete type instead of void*, there would be a warning.

Excellent example. This is a good enough reason to improve upon `void*` typedef.

> When you use void* you're basically opting out of type checking.

Clear enough.
I've been adding g++ compilation checks lately, because it is stricter regarding type casting.

>  I doubt there has ever been a system built where the alignment of a pointer to long long is different from the alignment of a pointer to a struct, but it is technically possible…

The pointer to `long long` wasn't meant to be a generic solution for any kind of pointer to private structure. This was supposed to be true for lz4frame context only, because it is the type with strictest alignment requirement within the structure.

But anyway, I'm sold to incomplete typedef. It feels cleaner methodology for private structure members.

**Comment by nemequ** [comment]
> Clear enough.
> I've been adding g++ compilation checks lately, because it is stricter regarding type casting.

Not sure if you care (probably not), but I just found the relevant part of the C11 spec; § 6.3.2.3, paragraph 1:

> A pointer to void may be converted to or from a pointer to any object type.  A pointer to any object type may be converted to a pointer to void and back again; the result shall compare equal to the original pointer.

**Comment by Cyan4973** [comment]
Thanks for underlining the relevant spec paragraph.

I remember this sentence. Initially, I was reading it as being applicable only to the "value of the pointer" (i.e. the memory address). I wasn't thinking about the "attached properties", such as "the memory following this address is storing `struct A` members", which is lost when converted to `void*`.

The ability to convert _from_ `void*`to any other pointer type seems to imply it acts as a wildcard to rebuild any kind of property attached to the more defined pointer type.

**Comment by Cyan4973** [comment]
Regarding function names : 
I believe I've made up my mind, and will probably go for : 
````
LZ4_compress_default()
LZ4_compress_fast()
LZ4_compress_fast_extState()
LZ4_compress_fast_continue()
````

`LZ4_compress_default()` sole benefit is to not require any acceleration value, both reducing the number of parameters, and avoiding the user to be aware and understand what this value could mean.
There is also a small chance that inlining will improve speed of this version, although this will have to be checked with benchmarks.

> A define for something like LZ4F_ACCELERATION_DEFAULT could also help make the API a bit more self-documenting

There is an `ACCELERATION_DEFAULT` defined within `lz4.c`. Do you mean it should be within `lz4.h` instead ?
I'm also considering that, if `LZ4_compress_fast()` is now the common prototype, I should probably change the policy regarding `ACCELERATION_DEFAULT` value, to make it the equivalent of `LZ4_compress_default()`

> One thing that is a bit confusing is that a higher value means faster but worse compression. I think everyone is used to a higher value correspond to slower, but better compression. 

That's a good point.

Btw, the way I intend to include `LZ4_compress_fast()` within lz4frame is by using negative compression level values : negative values will be interpreted as `-acceleration`. This way, the more negative, the worse the compression. So it will naturally blend with positive values (which lead to `LZ4_compress_HC()`).

But for `LZ4_compress_fast()`, I feel a bit stuck. It would seem strange to change "acceleration" as a negative-only value on this interface, with no use for positive values.

The difference is the name of the parameter : lz4frame (and lz4hc) require a "compression level", like zlib, xz, bzip, etc. On the other end, `LZ4_compress_fast()` requires an "acceleration", which is quite simply a different name for a different parameter. I believe the name of the parameter looks like a good hint, which expresses that a positive value means faster speed, albeit at the cost of some compression ratio.

**Comment by Cyan4973** [comment]
I've updated `lz4.h` API to reflect latest proposal discussed here.
See https://github.com/Cyan4973/lz4/blob/dev/lib/lz4.h

`lz4hc.h` will have to be modified in an equivalent way,
and client programs will then be updated.

**Comment by Cyan4973** [comment]
Finally updated `lz4hc` API.
The result can be consulted within the dev branch : 
https://github.com/Cyan4973/lz4/blob/dev/lib/lz4hc.h

The following naming convention was selected :
````
LZ4_compress_HC()
LZ4_compress_HC_extStateHC()
LZ4_compress_HC_continue()
````

There are now strong similarities between `LZ4_compress_fast()` and `LZ4_compress_HC()`. Prototypes feel almost identical.

**Comment by Cyan4973** [comment]
Well, now that I've changed most function names,
I was wondering if I should use the opportunity to also change a few arguments types.

For example, i/o buffer types could be moved from `char*` to `void*`, which is more generic, and should prove harmless for most existing user codes (keeping in mind older prototypes and still there and supported, so the question is more for people willing to adapt to the new API).
